#! /bin/bash
sudo cp -vpf --remove-destination \
  ~/src/aspireone/mkinitcpio.conf \
  /etc/mkinitcpio.conf
sudo cp -vpf --remove-destination \
  ~/src/aspireone/grub \
  /etc/default/grub
sudo cp -vpf --remove-destination \
  ~/src/aspireone/fstab \
  /etc/fstab
sudo cp -vpf --remove-destination \
  ~/src/aspireone/crypttab \
  /etc/crypttab

sudo chattr -i /etc/resolv.conf
sudo cp -vpf --remove-destination \
  ~/src/aspireone/resolv.conf \
  /etc/resolv.conf
sudo chattr +i /etc/resolv.conf

sudo cp -vpf --remove-destination \
  ~/src/aspireone/systemd/logind.conf \
  /etc/systemd/logind.conf
sudo cp -vpf --remove-destination \
  ~/src/aspireone/systemd/kbdrate.service \
  /etc/systemd/system/kbdrate.service
sudo cp -vpf --remove-destination \
  ~/src/aspireone/X11/70-synaptics.conf \
  /etc/X11/xorg.conf.d/70-synaptics.conf
sudo cp -vpf --remove-destination \
  ~/src/aspireone/torrc \
  /etc/tor/torrc
sudo cp -vpf --remove-destination \
  ~/src/aspireone/systemd/override.conf \
  /etc/systemd/system/getty@tty1.service.d/override.conf
sudo cp -vpf --remove-destination \
  ~/src/aspireone/20-quiet-printk.conf \
  /etc/sysctl.d/20-quiet-printk.conf
sudo cp -vpf --remove-destination \
  ~/src/aspireone/systemd/systemd-fsck-root.service \
  /etc/systemd/system/systemd-fsck-root.service
sudo cp -vpf --remove-destination \
  ~/src/aspireone/systemd/systemd-fsck@.service \
  /etc/systemd/system/systemd-fsck@.service
sudo cp -vpf --remove-destination \
  ~/src/aspireone/systemd/journald.conf \
  /etc/systemd/journald.conf
sudo cp -vpf --remove-destination \
  ~/src/aspireone/ntp.conf \
  /etc/ntp.conf
sudo cp -vpf --remove-destination \
  ~/src/aspireone/82-cdrom.rules \
  /etc/udev/rules.d/82-cdrom.rules


sudo cp -vpf --remove-destination \
  ~/src/aspireone/privoxy/config \
  /etc/privoxy/config
sudo chown -hR privoxy:privoxy /etc/privoxy/config
sudo cp -vpf --remove-destination \
  ~/src/aspireone/privoxy/user.action \
  /etc/privoxy/user.action
sudo chown -hR privoxy:privoxy /etc/privoxy/user.action

mkdir -p ~/.local/share/DisplayCAL/
if [ ! -d ~/.local/share/DisplayCAL/storage ]; then ln -svf \
  ~/src/aspireone/DisplayCAL/storage/ \
  ~/.local/share/DisplayCAL/storage > /dev/null 2>&1; fi
ln -svf ~/src/aspireone/DisplayCAL/spyd2PLD.bin \
  ~/.local/share/color/spyd2PLD.bin
